### ISSUE TITLE
Can't resize applet

### ISSUE THREAD

**Issue by dblsaiko** [crbble/stdout5#2]
The applet doesn't seem to be resizable, the text goes beyond the white area:
http://i.imgur.com/GJN0QrA.png

**Comment by crbble** [comment]
Sorry for the long delay.

Unlock the Desktop widgets, long press some corner of the widget and you get the three buttons for Settings, Resize, Rotate and removing the applet.

**Comment by dblsaiko** [comment]
Oh, thanks! Didn't know that was there.
